version: "3.0"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  instances-consumer:
    image: instances-consumer:latest
    build: .
    environment:
      DB_URI: mongodb://mongodb:27017/jaws
    ports:
      - "80:80"
